// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.mtime.client.retail.contract.dto;

public final class CommonProtos {
  private CommonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InvokeResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool Success = 1;
    /**
     * <code>required bool Success = 1;</code>
     *
     * <pre>
     *是否成功
     * </pre>
     */
    boolean hasSuccess();
    /**
     * <code>required bool Success = 1;</code>
     *
     * <pre>
     *是否成功
     * </pre>
     */
    boolean getSuccess();

    // optional int32 ErrorCode = 2;
    /**
     * <code>optional int32 ErrorCode = 2;</code>
     *
     * <pre>
     *错误编码
     * </pre>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 ErrorCode = 2;</code>
     *
     * <pre>
     *错误编码
     * </pre>
     */
    int getErrorCode();

    // optional string ErrorInfo = 3;
    /**
     * <code>optional string ErrorInfo = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    boolean hasErrorInfo();
    /**
     * <code>optional string ErrorInfo = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    java.lang.String getErrorInfo();
    /**
     * <code>optional string ErrorInfo = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrorInfoBytes();
  }
  /**
   * Protobuf type {@code InvokeResult}
   *
   * <pre>
   * 通用返回结果
   * </pre>
   */
  public static final class InvokeResult extends
      com.google.protobuf.GeneratedMessage
      implements InvokeResultOrBuilder {
    // Use InvokeResult.newBuilder() to construct.
    private InvokeResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InvokeResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InvokeResult defaultInstance;
    public static InvokeResult getDefaultInstance() {
      return defaultInstance;
    }

    public InvokeResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InvokeResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              errorCode_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              errorInfo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_InvokeResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_InvokeResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.class, com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.Builder.class);
    }

    public static com.google.protobuf.Parser<InvokeResult> PARSER =
        new com.google.protobuf.AbstractParser<InvokeResult>() {
      public InvokeResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InvokeResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InvokeResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool Success = 1;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>required bool Success = 1;</code>
     *
     * <pre>
     *是否成功
     * </pre>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool Success = 1;</code>
     *
     * <pre>
     *是否成功
     * </pre>
     */
    public boolean getSuccess() {
      return success_;
    }

    // optional int32 ErrorCode = 2;
    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>optional int32 ErrorCode = 2;</code>
     *
     * <pre>
     *错误编码
     * </pre>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 ErrorCode = 2;</code>
     *
     * <pre>
     *错误编码
     * </pre>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    // optional string ErrorInfo = 3;
    public static final int ERRORINFO_FIELD_NUMBER = 3;
    private java.lang.Object errorInfo_;
    /**
     * <code>optional string ErrorInfo = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    public boolean hasErrorInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string ErrorInfo = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    public java.lang.String getErrorInfo() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ErrorInfo = 3;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrorInfoBytes() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      success_ = false;
      errorCode_ = 0;
      errorInfo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorInfoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorInfoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InvokeResult}
     *
     * <pre>
     * 通用返回结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mtime.client.retail.contract.dto.CommonProtos.InvokeResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_InvokeResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_InvokeResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.class, com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.Builder.class);
      }

      // Construct using com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        errorInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_InvokeResult_descriptor;
      }

      public com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult getDefaultInstanceForType() {
        return com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.getDefaultInstance();
      }

      public com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult build() {
        com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult buildPartial() {
        com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult result = new com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorInfo_ = errorInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult) {
          return mergeFrom((com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult other) {
        if (other == com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorInfo()) {
          bitField0_ |= 0x00000004;
          errorInfo_ = other.errorInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool Success = 1;
      private boolean success_ ;
      /**
       * <code>required bool Success = 1;</code>
       *
       * <pre>
       *是否成功
       * </pre>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool Success = 1;</code>
       *
       * <pre>
       *是否成功
       * </pre>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool Success = 1;</code>
       *
       * <pre>
       *是否成功
       * </pre>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool Success = 1;</code>
       *
       * <pre>
       *是否成功
       * </pre>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // optional int32 ErrorCode = 2;
      private int errorCode_ ;
      /**
       * <code>optional int32 ErrorCode = 2;</code>
       *
       * <pre>
       *错误编码
       * </pre>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 ErrorCode = 2;</code>
       *
       * <pre>
       *错误编码
       * </pre>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 ErrorCode = 2;</code>
       *
       * <pre>
       *错误编码
       * </pre>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ErrorCode = 2;</code>
       *
       * <pre>
       *错误编码
       * </pre>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      // optional string ErrorInfo = 3;
      private java.lang.Object errorInfo_ = "";
      /**
       * <code>optional string ErrorInfo = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public boolean hasErrorInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ErrorInfo = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public java.lang.String getErrorInfo() {
        java.lang.Object ref = errorInfo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ErrorInfo = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorInfoBytes() {
        java.lang.Object ref = errorInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ErrorInfo = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public Builder setErrorInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ErrorInfo = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public Builder clearErrorInfo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorInfo_ = getDefaultInstance().getErrorInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ErrorInfo = 3;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public Builder setErrorInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorInfo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InvokeResult)
    }

    static {
      defaultInstance = new InvokeResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InvokeResult)
  }

  public interface AddInvokeResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .InvokeResult Result = 1;
    /**
     * <code>required .InvokeResult Result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required .InvokeResult Result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult getResult();
    /**
     * <code>required .InvokeResult Result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    com.mtime.client.retail.contract.dto.CommonProtos.InvokeResultOrBuilder getResultOrBuilder();

    // optional int32 Id = 2;
    /**
     * <code>optional int32 Id = 2;</code>
     *
     * <pre>
     *返回插入成功后主键Id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 Id = 2;</code>
     *
     * <pre>
     *返回插入成功后主键Id
     * </pre>
     */
    int getId();
  }
  /**
   * Protobuf type {@code AddInvokeResult}
   *
   * <pre>
   *通用插入返回结果
   * </pre>
   */
  public static final class AddInvokeResult extends
      com.google.protobuf.GeneratedMessage
      implements AddInvokeResultOrBuilder {
    // Use AddInvokeResult.newBuilder() to construct.
    private AddInvokeResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddInvokeResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddInvokeResult defaultInstance;
    public static AddInvokeResult getDefaultInstance() {
      return defaultInstance;
    }

    public AddInvokeResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddInvokeResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_AddInvokeResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_AddInvokeResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult.class, com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult.Builder.class);
    }

    public static com.google.protobuf.Parser<AddInvokeResult> PARSER =
        new com.google.protobuf.AbstractParser<AddInvokeResult>() {
      public AddInvokeResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddInvokeResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddInvokeResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .InvokeResult Result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult result_;
    /**
     * <code>required .InvokeResult Result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .InvokeResult Result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    public com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult getResult() {
      return result_;
    }
    /**
     * <code>required .InvokeResult Result = 1;</code>
     *
     * <pre>
     *返回结果
     * </pre>
     */
    public com.mtime.client.retail.contract.dto.CommonProtos.InvokeResultOrBuilder getResultOrBuilder() {
      return result_;
    }

    // optional int32 Id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 Id = 2;</code>
     *
     * <pre>
     *返回插入成功后主键Id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 Id = 2;</code>
     *
     * <pre>
     *返回插入成功后主键Id
     * </pre>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      result_ = com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.getDefaultInstance();
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getResult().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddInvokeResult}
     *
     * <pre>
     *通用插入返回结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_AddInvokeResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_AddInvokeResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult.class, com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult.Builder.class);
      }

      // Construct using com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_AddInvokeResult_descriptor;
      }

      public com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult getDefaultInstanceForType() {
        return com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult.getDefaultInstance();
      }

      public com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult build() {
        com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult buildPartial() {
        com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult result = new com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult) {
          return mergeFrom((com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult other) {
        if (other == com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult.getDefaultInstance()) return this;
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (!getResult().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mtime.client.retail.contract.dto.CommonProtos.AddInvokeResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .InvokeResult Result = 1;
      private com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult result_ = com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult, com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.Builder, com.mtime.client.retail.contract.dto.CommonProtos.InvokeResultOrBuilder> resultBuilder_;
      /**
       * <code>required .InvokeResult Result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .InvokeResult Result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>required .InvokeResult Result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public Builder setResult(com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .InvokeResult Result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public Builder setResult(
          com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .InvokeResult Result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public Builder mergeResult(com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              result_ != com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.getDefaultInstance()) {
            result_ =
              com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .InvokeResult Result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .InvokeResult Result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.Builder getResultBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>required .InvokeResult Result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      public com.mtime.client.retail.contract.dto.CommonProtos.InvokeResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>required .InvokeResult Result = 1;</code>
       *
       * <pre>
       *返回结果
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult, com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.Builder, com.mtime.client.retail.contract.dto.CommonProtos.InvokeResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult, com.mtime.client.retail.contract.dto.CommonProtos.InvokeResult.Builder, com.mtime.client.retail.contract.dto.CommonProtos.InvokeResultOrBuilder>(
                  result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // optional int32 Id = 2;
      private int id_ ;
      /**
       * <code>optional int32 Id = 2;</code>
       *
       * <pre>
       *返回插入成功后主键Id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 Id = 2;</code>
       *
       * <pre>
       *返回插入成功后主键Id
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 Id = 2;</code>
       *
       * <pre>
       *返回插入成功后主键Id
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Id = 2;</code>
       *
       * <pre>
       *返回插入成功后主键Id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AddInvokeResult)
    }

    static {
      defaultInstance = new AddInvokeResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AddInvokeResult)
  }

  public interface PageInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 PageIndex = 1;
    /**
     * <code>required int32 PageIndex = 1;</code>
     *
     * <pre>
     * 页码，从 1 开始
     * </pre>
     */
    boolean hasPageIndex();
    /**
     * <code>required int32 PageIndex = 1;</code>
     *
     * <pre>
     * 页码，从 1 开始
     * </pre>
     */
    int getPageIndex();

    // required int32 PageSize = 2;
    /**
     * <code>required int32 PageSize = 2;</code>
     *
     * <pre>
     * 每页大小
     * </pre>
     */
    boolean hasPageSize();
    /**
     * <code>required int32 PageSize = 2;</code>
     *
     * <pre>
     * 每页大小
     * </pre>
     */
    int getPageSize();
  }
  /**
   * Protobuf type {@code PageInfo}
   *
   * <pre>
   * 分页信息
   * </pre>
   */
  public static final class PageInfo extends
      com.google.protobuf.GeneratedMessage
      implements PageInfoOrBuilder {
    // Use PageInfo.newBuilder() to construct.
    private PageInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PageInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PageInfo defaultInstance;
    public static PageInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PageInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PageInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pageIndex_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pageSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_PageInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_PageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mtime.client.retail.contract.dto.CommonProtos.PageInfo.class, com.mtime.client.retail.contract.dto.CommonProtos.PageInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PageInfo> PARSER =
        new com.google.protobuf.AbstractParser<PageInfo>() {
      public PageInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PageInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PageInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 PageIndex = 1;
    public static final int PAGEINDEX_FIELD_NUMBER = 1;
    private int pageIndex_;
    /**
     * <code>required int32 PageIndex = 1;</code>
     *
     * <pre>
     * 页码，从 1 开始
     * </pre>
     */
    public boolean hasPageIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 PageIndex = 1;</code>
     *
     * <pre>
     * 页码，从 1 开始
     * </pre>
     */
    public int getPageIndex() {
      return pageIndex_;
    }

    // required int32 PageSize = 2;
    public static final int PAGESIZE_FIELD_NUMBER = 2;
    private int pageSize_;
    /**
     * <code>required int32 PageSize = 2;</code>
     *
     * <pre>
     * 每页大小
     * </pre>
     */
    public boolean hasPageSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 PageSize = 2;</code>
     *
     * <pre>
     * 每页大小
     * </pre>
     */
    public int getPageSize() {
      return pageSize_;
    }

    private void initFields() {
      pageIndex_ = 0;
      pageSize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPageIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPageSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, pageIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pageSize_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pageIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mtime.client.retail.contract.dto.CommonProtos.PageInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PageInfo}
     *
     * <pre>
     * 分页信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mtime.client.retail.contract.dto.CommonProtos.PageInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_PageInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_PageInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mtime.client.retail.contract.dto.CommonProtos.PageInfo.class, com.mtime.client.retail.contract.dto.CommonProtos.PageInfo.Builder.class);
      }

      // Construct using com.mtime.client.retail.contract.dto.CommonProtos.PageInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pageIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pageSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mtime.client.retail.contract.dto.CommonProtos.internal_static_PageInfo_descriptor;
      }

      public com.mtime.client.retail.contract.dto.CommonProtos.PageInfo getDefaultInstanceForType() {
        return com.mtime.client.retail.contract.dto.CommonProtos.PageInfo.getDefaultInstance();
      }

      public com.mtime.client.retail.contract.dto.CommonProtos.PageInfo build() {
        com.mtime.client.retail.contract.dto.CommonProtos.PageInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mtime.client.retail.contract.dto.CommonProtos.PageInfo buildPartial() {
        com.mtime.client.retail.contract.dto.CommonProtos.PageInfo result = new com.mtime.client.retail.contract.dto.CommonProtos.PageInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pageIndex_ = pageIndex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageSize_ = pageSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mtime.client.retail.contract.dto.CommonProtos.PageInfo) {
          return mergeFrom((com.mtime.client.retail.contract.dto.CommonProtos.PageInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mtime.client.retail.contract.dto.CommonProtos.PageInfo other) {
        if (other == com.mtime.client.retail.contract.dto.CommonProtos.PageInfo.getDefaultInstance()) return this;
        if (other.hasPageIndex()) {
          setPageIndex(other.getPageIndex());
        }
        if (other.hasPageSize()) {
          setPageSize(other.getPageSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPageIndex()) {
          
          return false;
        }
        if (!hasPageSize()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mtime.client.retail.contract.dto.CommonProtos.PageInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mtime.client.retail.contract.dto.CommonProtos.PageInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 PageIndex = 1;
      private int pageIndex_ ;
      /**
       * <code>required int32 PageIndex = 1;</code>
       *
       * <pre>
       * 页码，从 1 开始
       * </pre>
       */
      public boolean hasPageIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 PageIndex = 1;</code>
       *
       * <pre>
       * 页码，从 1 开始
       * </pre>
       */
      public int getPageIndex() {
        return pageIndex_;
      }
      /**
       * <code>required int32 PageIndex = 1;</code>
       *
       * <pre>
       * 页码，从 1 开始
       * </pre>
       */
      public Builder setPageIndex(int value) {
        bitField0_ |= 0x00000001;
        pageIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 PageIndex = 1;</code>
       *
       * <pre>
       * 页码，从 1 开始
       * </pre>
       */
      public Builder clearPageIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pageIndex_ = 0;
        onChanged();
        return this;
      }

      // required int32 PageSize = 2;
      private int pageSize_ ;
      /**
       * <code>required int32 PageSize = 2;</code>
       *
       * <pre>
       * 每页大小
       * </pre>
       */
      public boolean hasPageSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 PageSize = 2;</code>
       *
       * <pre>
       * 每页大小
       * </pre>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>required int32 PageSize = 2;</code>
       *
       * <pre>
       * 每页大小
       * </pre>
       */
      public Builder setPageSize(int value) {
        bitField0_ |= 0x00000002;
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 PageSize = 2;</code>
       *
       * <pre>
       * 每页大小
       * </pre>
       */
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageSize_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PageInfo)
    }

    static {
      defaultInstance = new PageInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PageInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_InvokeResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InvokeResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AddInvokeResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddInvokeResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PageInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\"E\n\014InvokeResult\022\017\n\007Succes" +
      "s\030\001 \002(\010\022\021\n\tErrorCode\030\002 \001(\005\022\021\n\tErrorInfo\030" +
      "\003 \001(\t\"<\n\017AddInvokeResult\022\035\n\006Result\030\001 \002(\013" +
      "2\r.InvokeResult\022\n\n\002Id\030\002 \001(\005\"/\n\010PageInfo\022" +
      "\021\n\tPageIndex\030\001 \002(\005\022\020\n\010PageSize\030\002 \002(\005B4\n$" +
      "com.mtime.client.retail.contract.dtoB\014Co" +
      "mmonProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_InvokeResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_InvokeResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_InvokeResult_descriptor,
              new java.lang.String[] { "Success", "ErrorCode", "ErrorInfo", });
          internal_static_AddInvokeResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_AddInvokeResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AddInvokeResult_descriptor,
              new java.lang.String[] { "Result", "Id", });
          internal_static_PageInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_PageInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PageInfo_descriptor,
              new java.lang.String[] { "PageIndex", "PageSize", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
